;; Auto generated based on org-babel literate config from emacs.org.
;; Do not edit this file.

;;--------------------------------------------------------------------------
;;  Visuals
;;--------------------------------------------------------------------------

;; Theme
(add-to-list 'custom-theme-load-path "~/dotfiles/.emacs.d/julien-theme.el")

;; UI
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)

(global-hl-line-mode t)

;; Startup - Start Page
(setq inhibit-startup-message t)
(setq inhibit-splash-screen t)
(setq initial-buffer-choice "~/.emacs.d/start.org")


;; Set the default font
(set-face-attribute 'default nil
                    :family "Iosevka"
                    :height 130)
;; Set color for selected region
(set-face-attribute 'region nil
                    :background "#424140")
;; Set color for current line (where the cursor is)
(set-face-background hl-line-face "gray13")

;;(set-frame-parameter (selected-frame) 'alpha '(80 . 79))

(defvar blink-cursor-colors (list "#FFFFFF" "#FF7F00")
  "On each blink the cursor will cycle to the next color in this list.")
(setq blink-cursor-count 0)
(defun blink-cursor-timer-function ()
  (when (not (internal-show-cursor-p))
    (when (>= blink-cursor-count (length blink-cursor-colors))
      (setq blink-cursor-count 0))
    (set-cursor-color (nth blink-cursor-count blink-cursor-colors))
    (setq blink-cursor-count (+ 1 blink-cursor-count)))
  (internal-show-cursor nil (not (internal-show-cursor-p))))

;; Displays the key bindings following your currently entered incomplete command (a prefix) in a popup
(use-package which-key
  :ensure t
  :config
  (which-key-mode))

;;--------------------------------------------------------------------------
;;  Default options
;;--------------------------------------------------------------------------

;; Package Management
(require 'package)
(add-to-list 'package-archives
  		       '("melpa"."https://melpa.org/packages/"))
;; Bootstrap use-package
(unless (package-installed-p 'use-package))

(add-hook 'before-save-hook 'delete-trailing-whitespace)

;; Write backups to ~/.emacs.d/backup/ to no clutter working directories
(setq backup-directory-alist '(("." . "~/.emacs.d/backup"))
      backup-by-copying      t  ; Don't de-link hard links
      version-control        t  ; Use version numbers on backups
      delete-old-versions    t  ; Automatically delete excess backups:
      kept-new-versions      20 ; how many of the newest versions to keep
      kept-old-versions      5) ; and how many of the old

;;Word Wrap
(add-hook 'text-mode-hook 'visual-line-mode)
(global-set-key (kbd "C-c w w") 'visual-line-mode)

;; swiper
(use-package swiper
  :ensure t
  :bind ("C-s" . swiper))

;; (use-package auto-complete
;;     :ensure t
;;    :config
;;    (ac-config-default)
;;    (global-auto-complete-mode 1))

(use-package company
  :ensure t
  :config
  (setq company-idle-delay 0)
  (setq company-minimum-prefix-length 3)
  (global-company-mode 1))

;;--------------------------------------------------------------------------
;;  Custom Commands
;;--------------------------------------------------------------------------

;; Refreshes Emacs config
(global-set-key (kbd "C-c e") (lambda () (interactive) (load-file "~/.emacs.d/init.el")))

;; Paste image from clipboard and save file in folder
(defun paste-image-from-clipboard ()
  "Paste an image from the clipboard as a file in the images/ folder."
  (interactive)
  (let* ((dir "./images/")  ;; Folder to save the image
         (filename (concat dir (make-temp-name "img-") ".png")))
    (unless (file-exists-p dir)
      (make-directory dir))  ;; Create the images folder if it doesn't exist
    (shell-command (concat "wl-paste --type image/png > " filename))  ;; Use wl-clipboard
    (insert (concat "[[file:" filename "]]"))
    (message "Image saved as %s" filename)))

(global-set-key (kbd "C-c [") 'paste-image-from-clipboard)
(setq vc-follow-symlinks t)
;;Renders Images inline of an org file
(defun do-org-show-all-inline-images ()
  (interactive)
  (org-display-inline-images t t))

;;--------------------------------------------------------------------------
  ;;  Programming and file editing
  ;;--------------------------------------------------------------------------

  ;; Conf-mode
  (add-to-list 'auto-mode-alist '("\\.gdextension\\'" . conf-mode))

  ;;(add-hook 'yaml-mode-hook 'yaml-pro-ts-mode 100)
(add-to-list 'auto-mode-alist '("\\.puml\\'" . wsd-mode))
(add-to-list 'auto-mode-alist '("\\.wsd\\'" . wsd-mode))
(add-to-list 'auto-mode-alist '("\\.ts\\'" . js-ts-mode))
(add-to-list 'auto-mode-alist '("Dockerfile\\'" . dockerfile-ts-mode))

(defun my-wsd-show-diagram-inline ()
  "Show the diagram inline after saving the buffer and save images to ~/.emacs.d/.temp."
  (when (and (derived-mode-p 'wsd-mode)
             (buffer-file-name))
    ;; Set the output directory for PNG files
    (let ((output-dir (expand-file-name "~/.emacs.d/.temp/")))
      (unless (file-exists-p output-dir)
        (make-directory output-dir t))
      (setq wsd-output-directory output-dir) ;; Assuming `wsd-output-directory` is the variable to set
      (wsd-show-diagram-inline)
      (display-buffer (get-buffer "*wsd-diagram*") '((display-buffer-in-side-window) . ((side . right) (slot . 0) (window-width . 50)))))))

(add-hook 'after-save-hook 'my-wsd-show-diagram-inline)

        (electric-pair-mode 1)

  ;;LaTex
  (setenv "PATH" (concat "/usr/local/texlive/2024/bin/x86_64-linux:" (getenv "PATH")))
  ;;(setq org-latex-packages-alist '(("" "fullpage") ("avoid-all" "widows-and-orphans") ("" "svg"))

  (setq-default company-backends '((company-bbdb :with company-yasnippet)
                                   (company-dabbrev company-ispell :with company-yasnippet)))

  ;; expand-region
  (use-package expand-region
    :bind ("C-=" . er/expand-region))

  ;; multiple-cursors
  (use-package multiple-cursors
    :ensure t
    :config
    (global-set-key (kbd "C->") 'mc/mark-next-like-this)
    (global-set-key (kbd "C-<") 'mc/mark-previous-like-this)
    (global-set-key (kbd "C-c C-<") 'mc/mark-all-like-this))

  ;;Identation
  (setq-default indent-tabs-mode nil)
  (setq-default tab-width 2)
  (setq indent-line-function 'insert-tab)

  (setq js-indent-level 2)

  ;; drag-stuff
  (drag-stuff-global-mode 1)
  (drag-stuff-define-keys )

  (when (require 'paredit nil t)
    (dolist (map (list lisp-mode-map emacs-lisp-mode-map))
      (define-key map (kbd "M-(")   'paredit-wrap-round)
      (define-key map (kbd "C-M-f") 'paredit-forward)
      (define-key map (kbd "C-M-b") 'paredit-backward)
      (define-key map (kbd "C-)")   'paredit-forward-slurp-sexp)
      (define-key map (kbd "C-M-)") 'paredit-forward-barf-sexp)
      (define-key map (kbd "C-(")   'paredit-backward-slurp-sexp)
      (define-key map (kbd "C-M-(") 'paredit-backward-barf-sexp)
      (define-key map (kbd "M-s s") 'paredit-split-sexp)
      (define-key map (kbd "M-s r") 'paredit-raise-sexp)
      (define-key map (kbd "M-s S") 'paredit-join-sexps)
      (define-key map (kbd "M-s J") 'paredit-join-sexps)
      (define-key map (kbd "M-s u") 'paredit-splice-sexp-killing-backward)
      (define-key map (kbd "M-s d") 'paredit-splice-sexp-killing-forward)
      (define-key map (kbd "M-q")   'paredit-reindent-defun)))

;; (use-package emacs-slack
;;   :bind (("C-c S K" . slack-stop)
;;          ("C-c S c" . slack-select-rooms)
;;          ("C-c S u" . slack-select-unread-rooms)
;;          ("C-c S U" . slack-user-select)
;;          ("C-c S s" . slack-search-from-messages)
;;          ("C-c S J" . slack-jump-to-browser)
;;          ("C-c S j" . slack-jump-to-app)
;;          ("C-c S e" . slack-insert-emoji)
;;          ("C-c S E" . slack-message-edit)
;;          ("C-c S r" . slack-message-add-reaction)
;;          ("C-c S t" . slack-thread-show-or-create)
;;          ("C-c S g" . slack-message-redisplay)
;;          ("C-c S G" . slack-conversations-list-update-quick)
;;          ("C-c S q" . slack-quote-and-reply)
;;          ("C-c S Q" . slack-quote-and-reply-with-link)
;;          (:map slack-mode-map
;;                (("@" . slack-message-embed-mention)
;;                 ("#" . slack-message-embed-channel)))
;;          (:map slack-thread-message-buffer-mode-map
;;                (("C-c '" . slack-message-write-another-buffer)
;;                 ("@" . slack-message-embed-mention)
;;                 ("#" . slack-message-embed-channel)))
;;          (:map slack-message-buffer-mode-map
;;                (("C-c '" . slack-message-write-another-buffer)))
;;          (:map slack-message-compose-buffer-mode-map
;;                (("C-c '" . slack-message-send-from-buffer)))
;;          )
;;   :custom
;;   (slack-extra-subscribed-channels (mapcar 'intern (list "some-channel")))
;;   :config
;;   (slack-register-team
;;      :name "clojurians"
;;      :token "xoxc-sssssssssss-88888888888-hhhhhhhhhhh-jjjjjjjjjj"
;;      :cookie "xoxd-sssssssssss-88888888888-hhhhhhhhhhh-jjjjjjjjjj; d-s=888888888888; lc=888888888888"
;;      :full-and-display-names t
;;      :default t
;;      :subscribed-channels nil ;; using slack-extra-subscribed-channels because I can change it dynamically
;;      ))

;; (use-package alert
;;   :commands (alert)
;;   :init
;;   (setq alert-default-style 'notifier))

;;--------------------------------------------------------------------------
  ;;  Org Mode
  ;;--------------------------------------------------------------------------

  (use-package org-bullets
  	:ensure t
  	:init
  	(setq org-bullets-bullet-list
  	      '("◉" "◎" "◇" "○" "►" "•"))
  	:config
  	(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))

(defun org-babel-execute:nix (body params)
  (let ((cmd (format "nix eval --raw --expr '%s'" body)))
    (org-babel-eval cmd "")))

  ;; active Babel languages
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((shell . t)
     (java . t)
     (plantuml . t)
     (nix . t)
     (gnuplot . t)))

  (setq org-plantuml-jar-path "~/.emacs.d/plantuml/plantuml.jar")

  (setq org-todo-keywords
        '((sequence "TODO(t)" "NEXT(n)" "WAIT(w)" "REDO(R)" "DONE(d)")))

  ;; Org Reveal
  ;;(require 'org-re-reveal)
  ;;(setq org-re-reveal-root "file:///home/julien/emacs/reveal.js-master")
  ;;(global-set-key (kbd "C-c n r") 'org-re-reveal-export-to-html)

  ;; org-present
  (unless (package-installed-p 'org-present)
    (package-install 'org-present))

  ;; Install visual-fill-column
  (unless (package-installed-p 'visual-fill-column)
    (package-install 'visual-fill-column))

  ;; Configure fill width
  (setq visual-fill-column-width 110
        visual-fill-column-center-text t)

  (defun my/org-present-start ()
    ;; Center the presentation and wrap lines
    (visual-fill-column-mode 1)
    (visual-line-mode 1))

  (defun my/org-present-end ()
    ;; Stop centering the document
    (visual-fill-column-mode 0)
    (visual-line-mode 0))

  ;; Register hooks with org-present
  (add-hook 'org-present-mode-hook 'my/org-present-start)
  (add-hook 'org-present-mode-quit-hook 'my/org-present-end)
  (global-set-key (kbd "C-c n p") 'org-present)

  ;; Org svg
  (defun svg-progress-percent (value)
    (save-match-data
      (svg-image (svg-lib-concat
                  (svg-lib-progress-bar  (/ (string-to-number value) 100.0)
                                         nil :margin 0 :stroke 2 :radius 3 :padding 2 :width 11)
                  (svg-lib-tag (concat value "%")
                               nil :stroke 0 :margin 0)) :ascent 'center)))

  (defun svg-progress-count (value)
    (save-match-data
      (let* ((seq (split-string value "/"))
             (count (if (stringp (car seq))
                        (float (string-to-number (car seq)))
                      0))
             (total (if (stringp (cadr seq))
                        (float (string-to-number (cadr seq)))
                      1000)))
        (svg-image (svg-lib-concat
                    (svg-lib-progress-bar (/ count total) nil
                                          :margin 0 :stroke 2 :radius 3 :padding 2 :width 11)
                    (svg-lib-tag value nil
                                 :stroke 0 :margin 0)) :ascent 'center))))

  ;; org-roam dependencies
  (use-package websocket
    :ensure t)

  (use-package simple-httpd
    :ensure t)

  (use-package org-roam
    :ensure t
    :custom
    (org-roam-directory "~/Documents/RoamNotes")
    (org-roam-completion-everywhere t)
    (org-roam-capture-templates
     '(("d" "default" plain
        "%?"
        :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+filetags: :default:")
        :unnarrowed t)
       ("e" "ets" plain
        ""
        :if-new (file+head "ets%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+filetags: :ets:")
        :unnarrowed t)
       ("n" "notes" plain
        ""
        :if-new (file+head "notes%<%Y-%m-%d_%H:%M:%S>-${slug}.org" "#+title: ${title}\n#+author:Secrétaire Julien Giguère\n#+LANGUAGE: fr\n#+filetags: :ets:notes:")
        :unnarrowed t)
       ("s" "saura" plain
        ""
        :if-new (file+head "saura%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+filetags: :saura:")
        :unnarrowed t)
       ))
    :bind (("C-c n l" . org-roam-buffer-toggle)
  	       ("C-c n f" . org-roam-node-find)
  	       ("C-c n i" . org-roam-node-insert)
  	       ("C-c n g" . org-roam-ui-mode)
  	       ("C-c n a" . org-roam-alias-add)
  	       ;; Dailies
  	       ("C-c n j" . org-roam-dailies-capture-today))
    :config
    (require 'org-roam-protocol)
    (org-roam-setup))
  ;; (add-to-list 'load-path "~/.emacs.d/gitclone/org-roam-ui/")
  ;; (load-library "org-roam-ui")

  (use-package org
    :commands (org-table-iterate-buffer-tables org-toggle-pretty-entities))

  (use-package org-roam-ui
    :commands (orui-open orui-node-local orui-node-zoom orui-sync-theme))

  (setq native-comp-async-report-warnings-errors nil)

  (require 'org-roam-export)
  (setq org-latex-packages-alist '(("margin=2cm" "geometry" nil)))
  (add-to-list 'org-latex-packages-alist '("AUTO" "babel" nil))
  (setq org-latex-toc-command "\\tableofcontents  \\clearpage")
  (define-key global-map (kbd "C-c n e") #'org-latex-export-to-pdf)

  ;; (define-key global-map (kbd "<f12>") #'org-transclusion-add)
  ;; (define-key global-map (kbd "C-c n t") #'org-transclusion-mode)
  ;; (add-hook 'org-mode-hook 'org-transclusion-mode)

;;--------------------------------------------------------------------------
;;  Global Keybindings - Hotkeys
;;--------------------------------------------------------------------------

(global-set-key (kbd "C-c i")
                'do-org-show-all-inline-images)

(global-set-key (kbd "C-c c")
                'comment-region)
(global-set-key (kbd "C-c u")
                'uncomment-region)

(global-set-key (kbd "C-c r") 'replace-string)

(global-set-key (kbd "C-c a") 'org-agenda)

;; (delete 'mu4e evil-collection-mode-list)
  ;; (delete 'mu4e-conversation evil-collection-mode-list)


(use-package mu4e
  :ensure nil
  ;; :load-path "/usr/share/emacs/site-lisp/mu4e/"
  ;; :defer 20 ; Wait until 20 seconds after startup
  :config

  ;; This is set to 't' to avoid mail syncing issues when using mbsync
  (setq mu4e-change-filenames-when-moving t)

  ;; Refresh mail using isync every 10 minutes
  (setq mu4e-update-interval (* 10 60))
  (setq mu4e-get-mail-command "mbsync -a")
  (setq mu4e-maildir "~/Mail")

  (setq mu4e-drafts-folder "/[Gmail]/Drafts")
  (setq mu4e-sent-folder   "/[Gmail]/Sent Mail")
  (setq mu4e-refile-folder "/[Gmail]/All Mail")
  (setq mu4e-trash-folder  "/[Gmail]/Trash")

  (setq mu4e-maildir-shortcuts
      '(("/Inbox"             . ?i)
        ("/[Gmail]/Sent Mail" . ?s)
        ("/[Gmail]/Trash"     . ?t)
        ("/[Gmail]/Drafts"    . ?d)
        ("/[Gmail]/All Mail"  . ?a))))

;;--------------------------------------------------------------------------
;;  Plugins
;;--------------------------------------------------------------------------


;;Discord Rich Presence
(use-package elcord
      :ensure t)

;;wiki info org
(use-package wikinforg
  :ensure t)

(global-set-key (kbd "C-c n w") 'wikinforg)

;; ;; Restclient
(use-package restclient
  :ensure t)
(use-package try
  :ensure t)
(add-to-list 'auto-mode-alist '("\\.http\\'" . restclient-mode))

;; gpt.el
(global-set-key (kbd "C-c p r") 'gptel-send-region)
(global-set-key (kbd "C-c p b") 'gptel-send-buffer)
(global-set-key (kbd "C-c p p") 'gptel)

;; helm
( use-package helm
  :ensure t)

;; avy
(use-package avy
  :ensure t)

;; ivy -vertico is good apparently-
(use-package ivy
  :ensure t
  :init
  (ivy-mode 1)
  :config
  (setq ivy-use-virtual-buffers t
        ivy-count-format "(%d/%d) "
        enable-recursive-minibuffers t))

(use-package transient
  :ensure t)
